<?php
// $Id$
/**
 * @file xdebug.module
 * TODO: Enter file description here.
 */

/**
 * Implementation of hook_boot().
 */
function xdebug_boot() {
  ini_set('html_errors', 1);
  variable_get('xdebug', array());

  if (filter_has_var(INPUT_GET, 'XDEBUG_TRACE')) {
    $file = ini_get('xdebug.trace_output_dir') .'/';
    $file .= filter_input(INPUT_GET, 'XDEBUG_TRACE', FILTER_SANITIZE_STRING);
    xdebug_start_trace($file);
  }
  if (filter_has_var(INPUT_GET, 'XDEBUG_CC_UNUSED')) {
    xdebug_start_code_coverage(XDEBUG_CC_UNUSED);
  } else if (filter_has_var(INPUT_GET, 'XDEBUG_CC_DEAD_CODE')) {
    xdebug_start_code_coverage(XDEBUG_CC_DEAD_CODE);
  }
  drupal_register_shutdown_function('xdebug_shutdown', TRUE);
}

/**
 * Shutdown function stops all xdebug behaviors.
 */
function xdebug_shutdown() {
  xdebug_stop_code_coverage(TRUE);
}
